language: node_js
node_js:
  - "4.1"
before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
before_script:
  - npm install -g gulp
  - npm install -g typescript@next
  - gulp build
script:
  - gulp host-api-test &
  - gulp host-imageUploader-test &
  - gulp host-imageServer-test &
  - node tests/test.js
services:
  - mongodb
  - redis-server
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
