export const parameterIsMissed = "the parameter '%s' is missed.";
export const parameterIsInvalid = "the parameter '%s' is invalid.";
export const theOrganizationIsPrivate = "the organization is private and only available to its members.";
export const theThemeIsNotOwnedByYou = "the theme is not owned by you.";
export const unauthorized = "the authentication credential is missed, out of date or invalid, or the access token is missed, invalid or out of scope.";
export const invalidIP = "your ip %s in not in the white list.";
export const theOrganizationNameAlreadyExists = "the organization name already exists.";
export const noFile = "no file.";
export const unexpectedError = "something happens unexpectedly.";
